In [20]:
import requests
from bs4 import BeautifulSoup
import csv
import pandas as pd

In [4]:
for page in range(1,6):
    print(page)

1
2
3
4
5

In [10]:
def timesjobsearch(searchString,exp,numofjobsperpage=20,numofpages=5):
   
    try:
        file = open(searchString+'.csv','w',newline='')
        writer = csv.writer(file)
        writer.writerow(['Job Role','Company Name','Key Skills','Experience','Location','Job Posted','Job Link'])
        
        for page in range(1, numofpages+1):
            url = requests.get("https://www.timesjobs.com/candidate/job-search.html?from=submit&luceneResultSize="+str(numofjobsperpage)+"&cboWorkExp1="+str(exp)+"&postWeek=30&txtKeywords="+searchString+"&sequence="+str(page)).text
            soup = BeautifulSoup(url, 'html')
            jobs = soup.find_all('li', class_ = 'clearfix job-bx wht-shd-bx')

            for job in jobs:
                try:
                    job_role = job.find('header', class_ = 'clearfix').h2.text.strip()
                except:
                    job_role = "Job Role not specified"

                try:
                    company_name = job.find('h3', class_ = 'joblist-comp-name').text.replace('(More Jobs)','').strip()
                except:
                    company_name = "Company Name not specified"

                try:
                    key_skills = job.find('span', class_ = 'srp-skills').text.replace(' ','').strip()
                except:
                    key_skills = "Skills not specified"

                try:
                    experience = job.find('ul', class_ = 'top-jd-dtl clearfix').li.text.replace('card_travel','')
                except:
                    experience = "Experience not specified"

                try:
                    location = job.find('ul', class_ = 'top-jd-dtl clearfix').span.text
                except:
                    location = 'Location not Specified'

                try:
                    job_posted = job.find('span', class_ = 'sim-posted').span.text.replace('Work From Home','').strip()
                except:
                    job_posted = "Not Specified"

                try:
                    job_link = job.header.h2.a['href']
                except:
                    job_link = "Link no specified"

                writer.writerow([job_role,company_name,key_skills,experience,location,job_posted,job_link])

        file.close()
        print(searchString+'.csv with '+str(exp)+' experience file created.')

    except:
        print('''Something went wrong.

Try reducing numofpages or numofjobsperpage(max value is 200).

If not specified, the default values are numofjobsperpage=10, numofpages=5 that will result in total 100 jobs.

If reducing the above values doesnt work then i dont know. Check the code yourself :)''')

In [7]:
timesjobsearch('Data Analyst',0)

Data Analyst.csv with 0 experience file created.

In [28]:
data = pd.read_csv('Data Analyst.csv')
data.head(5)

,Job Role,Company Name,Key Skills,Experience,Location,Job Posted,Job Link
0,Data Analyst,Fine Jobs Consultant Pvt. Ltd.,"dataanalysis,consulting,itconsulting,dataanaly...",0 - 3 yrs,Noida/Greater Noida,Posted 6 days ago,https://www.timesjobs.com/job-detail/data-anal...
1,Data Analyst,Cognizant Technology Solutions,"businessmanagement,excel,mis,DataAnalyst",0 - 3 yrs,Kolkata,Posted few days ago,https://www.timesjobs.com/job-detail/data-anal...
2,Data Analyst,ikomet Technology Solutions Pvt. Ltd.,"macros,visualization,bi,dataanalyst,vba",0 - 3 yrs,Chennai,Posted few days ago,https://www.timesjobs.com/job-detail/data-anal...
3,Data Analyst,Cargill India Pvt. Ltd.,"visualization,businessrequirements,datawarehou...",0 - 3 yrs,Bengaluru / Bangalore,Posted few days ago,https://www.timesjobs.com/job-detail/data-anal...
4,Data Analyst,McKinsey & Company Inc,"informationtechnology,usecases,dataanalytics,c...",0 - 2 yrs,NaN,Posted few days ago,https://www.timesjobs.com/job-detail/data-anal...

In [101]:
timesjobsearch("Java",0,20)

Done

In [114]:
job_role = job.find('header', class_ = 'clearfix').h2.text.strip()
job_role

'Associate - Projects'

In [183]:
searchString = 'web'

for page in range(1,3):
        url = requests.get("https://www.timesjobs.com/candidate/job-search.html?from=submit&luceneResultSize=10&cboWorkExp1=0&postWeek=30&txtKeywords="+searchString+"&sequence="+str(page)).text
        soup = BeautifulSoup(url, 'html')
        jobs = soup.find_all('li', class_ = 'clearfix job-bx wht-shd-bx')
    
        for job in jobs:
            job_role = job.find('header', class_ = 'clearfix').h2.text.strip()
            company_name = job.find('h3', class_ = 'joblist-comp-name').text.replace('(More Jobs)','').strip()
            key_skills = job.find('span', class_ = 'srp-skills').text.replace(' ','').strip()
            experience = job.find('ul', class_ = 'top-jd-dtl clearfix').li.text.replace('card_travel','')
            location = job.find('ul', class_ = 'top-jd-dtl clearfix').span.text
            job_posted = job.find('span', class_ = 'sim-posted').span.text.replace('Work From Home','').strip()
            job_link = job.header.h2.a['href']

        print(job_role, company_name, key_skills, experience, location, job_posted, job_link,'\n')

Web Designer webindia master webdesigner,indesign,3d,graphicdesigning,webdesigning,website,ux,photoshop,designing,maya,webtechnologies,wireframes,css3,illustrator 0 - 3 yrs Delhi Posted few days ago https://www.timesjobs.com/job-detail/web-designer-webindia-master-delhi-0-to-3-yrs-jobid-TmvuK0qBQCxzpSvf__PLUS__uAgZw==&source=srp

Web Designers Inzynix It Solutions photoshop,webdesigning,QuickLearning 0 - 3 yrs Thiruvananthapuram Posted few days ago https://www.timesjobs.com/job-detail/web-designers-inzynix-it-solutions-thiruvananthapuram-0-to-3-yrs-jobid-Lq__PLUS____SLASH__ZNai5kxzpSvf__PLUS__uAgZw==&source=srp

In [190]:
sal = job.find('ul', class_ = "top-jd-dtl clearfix").li.i['material-icons rupee']text
sal

SyntaxError: invalid syntax (<ipython-input-190-a413748e08bb>, line 1)

In [73]:
import pandas as pd

In [98]:
data = pd.read_csv('Data Analyst.csv')
data.head(40)

,Company Name,Key Skills,Experience,Location,Job Posted,Job Link
0,Fine Jobs Consultant Pvt. Ltd.,"dataanalysis,consulting,itconsulting,dataanaly...",0 - 3 yrs,Noida/Greater Noida,Posted 5 days ago,https://www.timesjobs.com/job-detail/data-anal...
1,Cognizant Technology Solutions,"businessmanagement,excel,mis,DataAnalyst",0 - 3 yrs,Kolkata,Posted few days ago,https://www.timesjobs.com/job-detail/data-anal...
2,ikomet Technology Solutions Pvt. Ltd.,"macros,visualization,bi,dataanalyst,vba",0 - 3 yrs,Chennai,Posted few days ago,https://www.timesjobs.com/job-detail/data-anal...
3,Cargill India Pvt. Ltd.,"visualization,businessrequirements,datawarehou...",0 - 3 yrs,Bengaluru / Bangalore,Posted few days ago,https://www.timesjobs.com/job-detail/data-anal...
4,McKinsey & Company Inc,"informationtechnology,usecases,dataanalytics,c...",0 - 2 yrs,NaN,Posted few days ago,https://www.timesjobs.com/job-detail/data-anal...
5,Stemmons Business Services Pvt. Ltd.,"businessrequirements,dataanalyst,database,data...",0 - 3 yrs,Vadodara,Posted few days ago,https://www.timesjobs.com/job-detail/data-anal...
6,Novotree Minds Consulting Private Limited,"dataanalysis,dashboards,dataanalyst,sql,advanc...",0 - 3 yrs,Bengaluru / Bangalore,Posted few days ago,https://www.timesjobs.com/job-detail/data-anal...
7,47Billion Information Technologies Pvt Ltd,"bigdataanalytics,datamining,storage,dashboards...",0 - 3 yrs,Indore,Posted few days ago,https://www.timesjobs.com/job-detail/data-anal...
8,ANR SOFTWARE PVT LTD,"dataanalytics,informationmanagement,sas,spss,d...",0 - 1 yrs,Noida/Greater Noida,Posted few days ago,https://www.timesjobs.com/job-detail/data-anal...
9,DYNATAC TECHNOLOGIES INDIA LIMITED,"visualization,informationtechnology,datastruct...",0 - 3 yrs,NaN,Posted few days ago,https://www.timesjobs.com/job-detail/data-anal...
10,QBE Insurance Group Limited,"reports,reporting,forecasting,stronganalytical...",0 - 3 yrs,NaN,Posted today,https://www.timesjobs.com/job-detail/data-anal...
11,flexera,"sql,salesforce,database,java,datastructures,ap...",0 - 3 yrs,NaN,Posted 1 day ago,https://www.timesjobs.com/job-detail/data-anal...
12,Cognizant Technology Solutions,"reports,mentor,customerinteraction,coding,data...",0 - 3 yrs,Kolkata,Posted 1 day ago,https://www.timesjobs.com/job-detail/data-anal...
13,QuEST Global Engineering Pvt Ltd,"RegulatedIndustriesinstruction,aerospace,techn...",0 - 2 yrs,NaN,Posted 1 day ago,https://www.timesjobs.com/job-detail/data-anal...
14,Cognizant Technology Solutions,"caseprocessing,clinicaltrials,cdm,clinical,pha...",0 - 3 yrs,Bengaluru / Bangalore,Posted 2 days ago,https://www.timesjobs.com/job-detail/data-anal...
15,Cognizant Technology Solutions,"caseprocessing,clinicaltrials,cdm,clinical,pha...",0 - 3 yrs,Bengaluru / Bangalore,Posted 2 days ago,https://www.timesjobs.com/job-detail/data-anal...
16,Cognizant Technology Solutions,"clinicaltrials,cdm,clinical,pharmacy,datamanag...",0 - 3 yrs,Hyderabad/Secunderabad,Posted 2 days ago,https://www.timesjobs.com/job-detail/data-anal...
17,Bloom Consulting Services,"datamining,writtencommunication,java,hadoop,te...",0 - 3 yrs,Bengaluru / Bangalore,Posted 6 days ago,https://www.timesjobs.com/job-detail/data-anal...
18,Hitwicket,"python,datamining,sql",0 - 3 yrs,Hyderabad/Secunderabad,Posted 3 days ago,https://www.timesjobs.com/job-detail/data-anal...
19,Mott MacDonald Group Ltd,"reports,datamanipulation,bi,formulas",0 - 3 yrs,Noida/Greater Noida,Posted 4 days ago,https://www.timesjobs.com/job-detail/data-anal...
20,mobileforce,"digitaldata,mediadata,dataanalysis",0 - 3 yrs,Indonesia,Posted 4 days ago,https://www.timesjobs.com/job-detail/data-anal...
21,Cognizant Technology Solutions,"clinicaltrials,clinicaldatamanagement,cdm,clin...",0 - 3 yrs,Mumbai,Posted 5 days ago,https://www.timesjobs.com/job-detail/data-anal...
22,SEVEN CONSULTANCY,"Definingnewdatacollection,Interpretationofcoll...",0 - 3 yrs,Hyderabad/Secunderabad,Posted 6 days ago,https://www.timesjobs.com/job-detail/data-anal...
23,Analytics Vidhya,"python,sas,datamining,ensemble,machinelearning...",0 - 2 yrs,Bengaluru / Bangalore,Posted 6 days ago,https://www.timesjobs.com/job-detail/data-anal...
24,TandA HR Solutions,"excel,audit,stronganalyticalskills.StrongDataM...",0 - 3 yrs,Chandigarh,Posted 6 days ago,https://www.timesjobs.com/job-detail/data-anal...
25,MINDWORKS GLOBAL MEDIA SERVICES,"algorithms,python,naturallanguageprocessing,ma...",0 - 3 yrs,Noida/Greater Noida,Posted 6 days ago,https://www.timesjobs.com/job-detail/data-anal...
26,Credit Suisse Securities ( India ) Pvt Ltd,"hive,html5,datamining,bi,devops,bigdata,python...",0 - 3 yrs,NaN,Posted 6 days ago,https://www.timesjobs.com/job-detail/data-anal...
27,advanced risk analytics private limited,"visualizingdata,datacollection,Flooddata",0 - 3 yrs,Pune,Posted 6 days ago,https://www.timesjobs.com/job-detail/data-anal...
28,Cognizant Technology Solutions,"clinicaltrials,cdm,clinical,pharmacy,datamanag...",0 - 3 yrs,Pune,Posted few days ago,https://www.timesjobs.com/job-detail/data-anal...
29,Beno Staffing,"reports,budgeting,financialprojections,profit,...",0 - 3 yrs,Ghaziabad,Posted few days ago,https://www.timesjobs.com/job-detail/data-anal...
30,Kwalee,"c,mobilegames,sql,jam,games,python,mobile,nosql",0 - 3 yrs,Bengaluru / Bangalore,Posted few days ago,https://www.timesjobs.com/job-detail/data-anal...
31,Cognizant Technology Solutions,"caseprocessing,clinicaltrials,cdm,clinical,pha...",0 - 3 yrs,Pune,Posted few days ago,https://www.timesjobs.com/job-detail/data-anal...
32,Cognizant Technology Solutions,"caseprocessing,clinicaltrials,cdm,clinical,pha...",0 - 3 yrs,Mumbai,Posted few days ago,https://www.timesjobs.com/job-detail/data-anal...
33,Cognizant Technology Solutions,"reports,mentor,customerinteraction,coding,data...",0 - 3 yrs,Mumbai,Posted few days ago,https://www.timesjobs.com/job-detail/data-anal...
34,Cognizant Technology Solutions,"clinicaltrials,clinicaldatamanagement,cdm,clin...",0 - 3 yrs,Mumbai,Posted few days ago,https://www.timesjobs.com/job-detail/data-anal...
35,BUSISOL SOURCING INDIA PVT. LTD,"charts,datamining,formulas,relationaldatabase,...",0 - 3 yrs,Mumbai,Posted few days ago,https://www.timesjobs.com/job-detail/data-anal...
36,Cognizant Technology Solutions,"caseprocessing,clinicaltrials,cdm,clinical,pha...",0 - 3 yrs,Hyderabad/Secunderabad,Posted few days ago,https://www.timesjobs.com/job-detail/data-anal...
37,BUSISOL SOURCING INDIA PVT. LTD,"reports,charts,datamining,formulas,reportingse...",0 - 3 yrs,Delhi,Posted few days ago,https://www.timesjobs.com/job-detail/data-anal...
38,Cognizant Technology Solutions,"clinicaltrials,cdm,clinical,pharmacy,datamanag...",0 - 3 yrs,Hyderabad/Secunderabad,Posted few days ago,https://www.timesjobs.com/job-detail/data-anal...
39,Hexanika,"testdata,sqlqueries,testing,sql",0 - 3 yrs,Pune,Posted few days ago,https://www.timesjobs.com/job-detail/data-anal...

In [ ]:
#        with open(searchString+'.csv','w',newline='') as f:
#            csv_writer = DictWriter(f,fieldnames=['Company Name','Key Skills','Experience','Location','Job Posted','Job Link'])
#            csv_writer.writeheader()
#            csv_writer.writerows(timesjobs)
#            print(f'Company Name: {company_name}\nKey Skills: {key_skills},\nExperience: {exp}\nLocation: {location}\nJob Posted: {job_posted}\nJob Link: {job_link}\n\n')